services:
  # backend
  # postgres db
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./src/db/postgres_data:/var/lib/postgresql/data
    container_name: postgres-mangify-dev

  # server
  server:
    image: mangify-server-dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3001:3001
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: mangify-server-dev
    environment:
      POSTGRES_HOST: postgres
