name: Testing pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Create temporary .env file
        env:
          MAIN_ENV: ${{ secrets.MAIN_ENV }}
        run: |
          echo "${MAIN_ENV}" > .env
      - name: Set up testing environment
        env:
          NODE_ENV: development
        run: |
          docker-compose -f docker-compose.dev.yml up -d  # Start the testing environment
      # - name: Run server linting
      #   run: |
      #     docker exec mangify-server-dev npm run lint
      - name: Run client linting
        run: |
          docker exec mangify-client-dev npm run lint
      - name: Run server tests
        run: |
          docker exec mangify-server-dev npm test
      - name: Run e2e tests
        run: |
          cd client
          npm run cypress:open
      - name: Clean up
        run: |
          docker-compose -f docker-compose.dev.yml down -v  # Stop and remove the testing environment
