name: Deployment pipeline

on:
  push:
    branches:
      - testing-cicd
  # pull_request:
  #   branches: [main]
  #   types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: SSH into VM and fetch latest source code
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{secrets.KEY}}
          username: ${{secrets.USERNAME}}
          host: ${{secrets.HOST}}
          script: |
            cd mangify
            git stash 2>&1 | grep -v "No local changes to save"
            git pull
            if git stash list | grep -q 'stash'; then
                git stash pop
            fi
      - name: SSH into VM and run deployment script
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{secrets.KEY}}
          username: ${{secrets.USERNAME}}
          host: ${{secrets.HOST}}
          script: |
            cd mangify
            chmod +x deploy.sh
            ./deploy.sh
  #     - name: test success
  #       uses: rjstone/discord-webhook-notify@v1
  #       if: success()
  #       with:
  #         severity: info
  #         text: A new version of the blog app deployed at http://49.13.59.65/
  #         webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  #     - name: test failture
  #       uses: rjstone/discord-webhook-notify@v1
  #       if: failure()
  #       with:
  #         severity: error
  #         text: Build failed
  #         description: commit ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].author.name }} broke the build :(
  #         webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  #
  # tag_release:
  #   needs: [deployment_pipeline]
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Bump version and push tag
  #       if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
  #       uses: anothrNick/github-tag-action@1.67.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DEFAULT_BUMP: patch
  #         WITH_V: true
